spring:
  application:
    name: kafka001
  datasource:
    url: jdbc:postgresql://localhost:5433/springboot_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  auth:
    jwt_secret: 83f1622a43889f83f151f57f241d5ee91d9a72a61124ddd76fe6900374fedf66
    jwt_expiration_time: 3600000
  data:
    jdbc:
      dialect: postgresql
  mvc:
    servlet:
      path: /api
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: "*"
            value:
              default:
                type: dev.hemraj.kafka_001.model.dto.platform.CreateOrderEvent
  mail:
    password: xxxx
    username: yourmail@gmail.com
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
logging:
  level:
    org:
      springframework:
        security: DEBUG
