spring:
  application:
    name: jwtAuthentication
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: mysql
server:
  port: 4000
security:
  jwt:
    secret-key: gCraGFn1oKzn/YwTY7kQprMnuHgWPV6ZdBtv82nmWPA=
    expiration-time: 86400000
logging:
  level:
    root: info
    dev.hemraj: debug
  file:
    name: auth.log
    path: /var/jwtauth/logs