spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: killerhems004@gmail.com
    password: hufo bgcb mqsf icag
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  application:
    name: jwtAuthentication
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: mysql
server:
  port: 4000
security:
  jwt:
    secret-key: gCraGFn1oKzn/YwTY7kQprMnuHgWPV6ZdBtv82nmWPA=
    expiration-time: 86400000
logging:
  level:
    root: info
    dev.hemraj: debug
  file:
    name: auth.log
    path: /var/jwtauth/logs


